# Generated by Django 3.0.4 on 2020-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200316_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='obp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='slg',
            field=models.FloatField(),
        ),
    ]
