# Generated by Django 3.0.4 on 2020-03-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200317_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
