# Generated by Django 3.0.4 on 2020-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200325_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(help_text='Who will be traveling on this journey', to='account.Profile'),
        ),
    ]
