# Generated by Django 3.0.4 on 2020-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200325_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(help_text='Ctrl + click to select multiple', to='account.Destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportation_methods',
            field=models.ManyToManyField(blank=True, help_text='Ctrl + click to select multiple', related_name='Travel_methods', to='account.Transportation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(help_text='Who will be traveling on this journey?', to='account.Profile'),
        ),
    ]
