# Generated by Django 3.0.4 on 2020-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200325_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Done', 'Trip has been completed'), ('Open', 'Trip is ongoing')], default='Open', max_length=4),
        ),
    ]
