# Generated by Django 3.0.4 on 2020-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200329_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='trip',
            field=models.ManyToManyField(help_text='On which trip will you be traveling to this destination?', to='account.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(help_text='Ctrl + click to select multiple', related_name='where_to', to='account.Destination'),
        ),
    ]
