# Generated by Django 3.0.4 on 2020-03-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200331_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='trip',
        ),
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(help_text='Ctrl + click to select multiple', to='account.Destination'),
        ),
    ]
