# Generated by Django 3.0.4 on 2020-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200404_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image/screenshot of your document', null=True, upload_to='account/docs'),
        ),
    ]
