# Generated by Django 3.0.3 on 2020-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200303_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
