# Generated by Django 3.0.4 on 2020-03-30 13:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_auto_20200329_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Select the day of the trip')),
                ('name', models.CharField(blank=True, help_text='Optional - give a name to remember what was/will be done on this day', max_length=200, null=True)),
                ('requirements', models.CharField(blank=True, help_text='List anything you may need to bring', max_length=500, null=True)),
                ('journal', models.CharField(blank=True, help_text='To be completed after - write any notes/memories from this day', max_length=1000, null=True)),
                ('contacts', models.ManyToManyField(blank=True, help_text='Ex: Tour company: 123-456-7890, Tour guide: 098-765-4321, etc.', null=True, to='itinerary.Contact')),
                ('destinations', models.ManyToManyField(blank=True, help_text='Ctrl + click to select multiple', null=True, to='account.Destination')),
                ('transportation_methods', models.ManyToManyField(blank=True, help_text='Ctrl + click to select multiple', related_name='DayTransportation', to='account.Transportation')),
            ],
        ),
    ]
