# Generated by Django 3.0.4 on 2020-03-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200329_1058'),
        ('itinerary', '0002_auto_20200330_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Trip'),
        ),
    ]
