# Generated by Django 3.0.4 on 2020-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_dayplan_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='name',
            field=models.CharField(default='test', help_text='Give a name to remember what was/will be done on this day', max_length=200),
            preserve_default=False,
        ),
    ]
