# Generated by Django 3.0.4 on 2020-03-31 08:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20200330_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='itinerary.Contact'),
        ),
    ]
