# Generated by Django 3.0.4 on 2020-03-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200331_0828'),
        ('itinerary', '0005_auto_20200331_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='trip',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='account.Trip'),
            preserve_default=False,
        ),
    ]
