# Generated by Django 3.0.4 on 2020-04-04 14:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_contact_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='(format: +12125552368)', max_length=128, region=None),
        ),
    ]
