# Generated by Django 3.0.3 on 2020-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
