# Generated by Django 3.0.3 on 2020-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='head',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
