# Generated by Django 3.0.4 on 2020-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.CharField(blank=True, help_text='Amount/size/description/etc', max_length=200, null=True),
        ),
    ]
