# Generated by Django 3.0.4 on 2020-03-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200325_1025'),
        ('spending', '0002_purchase_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_budget', to='account.Trip'),
        ),
    ]
