# Generated by Django 3.0.4 on 2020-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
