# Generated by Django 3.0.4 on 2020-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_player_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='funds',
            field=models.IntegerField(default=1000),
        ),
    ]
