# Generated by Django 3.0.4 on 2020-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_player_on_trade_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='in_offers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='out_offers',
            field=models.IntegerField(default=0),
        ),
    ]
