# Generated by Django 3.0.4 on 2020-03-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20200318_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], max_length=1)),
                ('money_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='roster',
        ),
        migrations.AddField(
            model_name='player',
            name='mlb_team',
            field=models.CharField(default='Free Agent', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Team'),
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
        migrations.AddField(
            model_name='offer',
            name='offering_players',
            field=models.ManyToManyField(related_name='Offers', to='trading.Player'),
        ),
        migrations.AddField(
            model_name='offer',
            name='requesting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Team'),
        ),
        migrations.AddField(
            model_name='offer',
            name='trade_block_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_block_player', to='trading.Player'),
        ),
    ]
