# Generated by Django 3.0.4 on 2020-03-19 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20200318_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='deciding_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deciding_team', to='trading.Team'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='requesting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_team', to='trading.Team'),
        ),
    ]
