# Generated by Django 3.0.4 on 2020-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20200319_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offering_players',
            field=models.ManyToManyField(blank=True, related_name='Offers', to='trading.Player'),
        ),
    ]
